from PIL import Image

#image=Image.open('unsplash_01.jpg')
# #thumbnail us better to use than resize because it also maintain the aspect ratio,resize blow out the image
# new_img=image.resize((400,300))
# new_img.save('new.jpg')
# new_img.show()
# image=Image.open('1.jpg')
# print(image.size)
# image.thumbnail((400,400))
# image.save('t1.jpg')
# box=(150,100,60,100)
# cropped_image
# image = Image.open('unsplash_01.jpg')
# logo = Image.open('logo.png')
# image_copy = image.copy()
# position = ((image_copy.width - logo.width), (image_copy.height - logo.height))
# image_copy.paste(logo, position,logo)
# image_copy.save('pasted_image.jpg')
# image_copy.paste(logo,position,logo)
# image = Image.open('1.jpg')
# box = (340, 120, 550, 290)
# cropped_image = image.crop(box)
# cropped_image.save('cropped_image.jpg')
# image=Image.open('cropped_image.jpg')
# image.thumbnail((100,100))
# image.save('up.jpg')
image=Image.open('new.jpg')
p=Image.open('up.jpg')
up=p.rotate(-60)
image_copy=image.copy()
position=(40,95)
image_copy.paste(up,position)
image_copy.save('final.jpg')